#!/usr/bin/env bash
set -euo pipefail

PROJECTS_DIR="/Volumes/d50-970p-1t/projects"
OUTPUT="$PROJECTS_DIR/CLAUDE.md"
CACHE_TTL=300

# Exit silently if projects drive isn't mounted
[ -d "$PROJECTS_DIR" ] || exit 0

# Skip if recently generated
if [ -f "$OUTPUT" ]; then
  now=$(date +%s)
  mod=$(stat -f %m "$OUTPUT" 2>/dev/null || echo 0)
  if (( now - mod < CACHE_TTL )); then
    exit 0
  fi
fi

own_rows=""
ref_rows=""
port_rows=""
db_rows=""

get_description() {
  local dir="$1"

  # Try CLAUDE.md: first non-empty, non-heading, non-boilerplate line (skip code blocks)
  if [ -f "$dir/CLAUDE.md" ]; then
    local desc
    desc=$(awk '/^```/{skip=!skip; next} skip{next} /^#/{next} /^$/{next} /^---/{next} /^<!--/{next} /provides guidance to Claude/{next} {print; exit}' "$dir/CLAUDE.md")
    if [ -n "$desc" ]; then
      echo "${desc:0:80}"
      return
    fi
  fi

  # Try package.json description
  if [ -f "$dir/package.json" ]; then
    local desc
    desc=$(sed -n 's/.*"description"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$dir/package.json" | head -1)
    if [ -n "$desc" ] && [ "$desc" != "null" ]; then
      echo "${desc:0:80}"
      return
    fi
  fi

  # Try go.mod module path
  if [ -f "$dir/go.mod" ]; then
    local mod
    mod=$(head -1 "$dir/go.mod" | sed 's/^module //')
    if [ -n "$mod" ]; then
      echo "$mod"
      return
    fi
  fi

  echo "-"
}

get_stack() {
  local dir="$1" stack=""
  [ -f "$dir/go.mod" ] && stack="Go" || true
  # Check for TS in root or common subdirs (web/, frontend/, client/, app/)
  local has_ts=false
  for tsdir in "$dir" "$dir/web" "$dir/frontend" "$dir/client" "$dir/app"; do
    if [ -f "$tsdir/tsconfig.json" ] || [ -f "$tsdir/tsconfig.base.json" ]; then
      has_ts=true
      break
    fi
  done
  if [ "$has_ts" = true ]; then
    stack="${stack:+$stack, }TS"
  elif [ -f "$dir/package.json" ]; then
    stack="${stack:+$stack, }JS"
  fi
  { [ -f "$dir/pyproject.toml" ] || [ -f "$dir/setup.py" ]; } && stack="${stack:+$stack, }Py" || true
  [ -f "$dir/Cargo.toml" ] && stack="${stack:+$stack, }Rust" || true
  { [ -f "$dir/Makefile" ] && [ -f "$dir/src/main.c" ]; } && stack="${stack:+$stack, }C" || true
  echo "${stack:--}"
}

is_own_project() {
  local dir="$1"
  [ ! -d "$dir/.git" ] && return 0
  local remote
  remote=$(git -C "$dir" remote get-url origin 2>/dev/null || echo "")
  [ -z "$remote" ] && return 0
  [[ "$remote" == *chris* ]] && return 0
  return 1
}

get_remote_source() {
  local dir="$1"
  local remote
  remote=$(git -C "$dir" remote get-url origin 2>/dev/null || echo "")
  echo "$remote" | sed -E 's|.*[:/]([^/]+/[^/]+)(\.git)?$|\1|'
}

extract_infra() {
  local dir="$1" name="$2"
  local compose=""
  [ -f "$dir/docker-compose.yml" ] && compose="$dir/docker-compose.yml"
  [ -f "$dir/docker-compose.yaml" ] && compose="$dir/docker-compose.yaml"
  [ -z "$compose" ] && return

  # Extract host ports
  local ports
  ports=$(grep -oE '"([0-9]+):[0-9]+"' "$compose" 2>/dev/null | tr -d '"' | cut -d: -f1 | sort -n | uniq || true)
  for p in $ports; do
    port_rows="${port_rows}| $p | $name |\n"
  done

  # Extract database names (skip generic 'postgres')
  local dbs
  dbs=$(grep -iE 'POSTGRES_DB:' "$compose" 2>/dev/null | sed 's/.*POSTGRES_DB:[[:space:]]*//' | tr -d ' "' | grep -v '^postgres$' || true)
  for db in $dbs; do
    db_rows="${db_rows}| $db | $name |\n"
  done
}

# Main scan loop
for dir in "$PROJECTS_DIR"/*/; do
  [ -d "$dir" ] || continue
  name=$(basename "$dir")

  [[ "$name" == .* ]] && continue
  [[ "$name" == "node_modules" ]] && continue

  stack=$(get_stack "$dir")
  desc=$(get_description "$dir")

  if is_own_project "$dir"; then
    extract_infra "$dir" "$name"
    own_rows="${own_rows}| ${name} | ${desc} | ${stack} |\n"
  else
    source=$(get_remote_source "$dir")
    ref_rows="${ref_rows}| ${name} | ${source} | ${stack} |\n"
  fi
done

# Sort rows and strip empty lines
sorted_own=$(echo -e "$own_rows" | grep -v '^$' | sort -t'|' -k2 || true)
sorted_ref=$(echo -e "$ref_rows" | grep -v '^$' | sort -t'|' -k2 || true)
sorted_db=$(echo -e "$db_rows" | grep -v '^$' | sort -t'|' -k2 || true)
sorted_ports=$(echo -e "$port_rows" | grep -v '^$' | sort -t'|' -k2 -n || true)

timestamp=$(date '+%Y-%m-%d %H:%M')
cat > "$OUTPUT" << CATALOG
# Projects Catalog
<!-- Auto-generated by project-awareness plugin | ${timestamp} | Do not edit manually -->

## My Projects
| Project | Description | Stack |
|---------|-------------|-------|
${sorted_own}

## Reference / Forked
| Project | Source | Stack |
|---------|--------|-------|
${sorted_ref}

## Infrastructure

### Shared Services (N100 — 192.168.130.160)
- Postgres 16 on \`shared\` Docker network
- Redis 7.4 on \`shared\` Docker network

### Databases (from local dev compose files)
| Database | Project |
|----------|---------|
${sorted_db}

### Port Allocations (from local dev compose files)
| Port | Project |
|------|---------|
${sorted_ports}
CATALOG
